### ISSUE TITLE
[Research] Flutterflow - Explore the possibility that pdfviewer can load pdf file from local storage

### ISSUE THREAD

**Issue by atnanahidiw** [ia-toki/bebras-pandai#1]
### Description
Basically, this task is intended to explore the feasibility of accessing local file / storage in Flutterflow
But to be more specific & visible, the scope is focused on loading pdf from local storage

#### Flows
- Minimal flow:
several files in local storage -> loaded by pdfviewer dynamically
- Near-complete flow:
download pdf file using firebase -> saved to local storage -> loaded by pdfviewer dynamically

### Deliveries:
- P0, document of the exploration + reference
- P1, better if we could find a hacky way to make the task a success
- P100 (optional, plus point), some suggestions on how to use Flutterflow in the future

**Comment by atnanahidiw** [comment]
@azophy bisa diupdate juga progressnya dikomen sini 🙇

**Comment by azophy** [comment]
baru early exploration. notes nya insya Allah diupdate di sini: https://azophy.notion.site/Bebras-254d2343f589408fb7af3bc8ec482c24?pvs=4

**Comment by atnanahidiw** [comment]
https://github.com/ia-toki/bebras-pandai/issues/1#issuecomment-1675691452
ntabz 👍👍👍
