### ISSUE TITLE
[Task] Make Homepage & UnderConstruction page

### ISSUE THREAD

**Issue by atnanahidiw** [ia-toki/bebras-pandai#10]
### Description
Make the following page after a successful login
![Image](https://user-images.githubusercontent.com/1970083/265899599-b8b5ff93-d134-4584-9266-125fbcce3a57.png)

But if the button is clicked it will redirect to a page like this
![Image](https://user-images.githubusercontent.com/1970083/265899773-27c69d5b-12e2-408e-a142-d613b53bcc7a.png)

### Deliveries:
The pages are created

**Comment by ArvinCS** [comment]
What does the hyperlink "Tentang Bebras Indonesia" refer to?
