### ISSUE TITLE
Remove Question Content from Task Structure

### ISSUE THREAD

**Issue by gmochid** [ia-toki/bebras-pandai#104]
Short Description
1. Remove Question Content dari Firebase by @haqqer 
2. Move App implementation to remove task.question.content

**Comment by temanaziz** [comment]
Question content akan dipisah dari Description Content

**Comment by temanaziz** [comment]
Perlu menghapus bagian question di pop up jawaban
![image](https://github.com/ia-toki/bebras-pandai/assets/137871192/82c1457c-e44e-487e-8ec1-e21be051c74a)

**Comment by gmochid** [comment]
Ini kita lakukannya di Frontend Aplikasi aja deh. Mungkin logic-nya, jika ada field "Question", maka content-nya tampil di popup. Otherwise tidak perlu ada yang tampil @1234iqbal

**Comment by temanaziz** [comment]
Sementara field question content kita gabungkan dengan description content, sehingga question content ini tidak kita pakai dulu.
