### ISSUE TITLE
Loading Image

### ISSUE THREAD

**Issue by temanaziz** [ia-toki/bebras-pandai#105]
1. User have to be able to see image in the question
2. User have to be able to see image in the answer choice

**Comment by temanaziz** [comment]
Loading image di jawaban masih perlu ganti struktur dokumen

**Comment by gmochid** [comment]
Untuk bisa parsing image yang ada di XML Document itu cukup sulit, sehingga sebaiknya proses parsin dilakukan secara manual saja. Dan proses memasukkan soal dilakukan proofreading secara manual oleh manusia.

Proofreader ini juga bertanggung jawab untuk memasukkan datanya ke Firebase sesuai dengan format yang tepat
