### ISSUE TITLE
Rule of Quitting in the Middle of Test

### ISSUE THREAD

**Issue by temanaziz** [ia-toki/bebras-pandai#109]
Peserta yang sudah klik "Mulai" pada latihan, jika akan keluar akan membaca popup:
"Anda akan keluar dari latihan. Latihan akan dianggap selesai dengan hasil seadanya. Apakah Anda setuju? Y/N"

Jika peserta menekan tombol Ya, latihan akan dianggap selesai dan hasil akan dihitung seadanya.

**Comment by gmochid** [comment]
Keluar ini kan ada 2 definisi ya
1. Menutup aplikasi  dengan swipe up
2. Menutup menu soal kembali ke menu sebelumnya

Kita mau handle kedua case ini? Atau seperti apa? @temanaziz

**Comment by gmochid** [comment]
Decision

1. Menutup aplikasi dengan swipe up
    - Training aka otomatis dibuat selesai
2. Menutup menu soal kembali ke menu sebelumnya
    - Peserta akan mendapatkan popup "Anda akan keluar dari latihan. Latihan akan dianggap selesai dengan hasil seadanya. Apakah Anda setuju? Y/N".
    - Jika user memilih Ya, maka akan keluar dari test dan penilaian akan dilakukan
    - Jika user memilih Tidak, maka akan stay di pengerjaan soal
