### ISSUE TITLE
Add property to control which task is included in the Weekly Rotation

### ISSUE THREAD

**Issue by gmochid** [ia-toki/bebras-pandai#116]
Since not all of the question available is ready to be presented to the end user just yet. We need to filter out which question is included in the weekly rotation. Probably with some boolean would just works.

- [ ] Questions flagged with not showing should not be included in weekly rotation

**Comment by gmochid** [comment]
Property yang akan digunakan untuk membedakan mana yang published ataupun tidak adalah `active`

**Comment by atnanahidiw** [comment]
Bagaimana kalau kita bikin enum dan nama propertynya `proofread_status`?

Lebih enak bisa cover beberapa usecases:
1. weekly rotation -> filter `proofread_status in ('READY')` di script
2. buat admin di HP -> filter `proofread_status in ('READY', 'NEED_REVIEW', 'NEED_EDIT')` (mungkin buat dibaca sama script yg bikin `task_set_doc_index`)
3. baru awal bikin mungkin statusnya `'DRAFT'`
4. bisa nambah2in menu lain eksplisit

**Comment by haqqer** [comment]
@atnanahidiw kalau disimplify jadi `status` aja gimana mas?

**Comment by atnanahidiw** [comment]
Bisa juga mas @haqqer 👍 👍 👍 
Valid value nya apa aja nih? Kalau usul saya pakai value yg verbose:
- `draft`
- `need_review`
- `need_edit`
- `ready`
- `reserve`
- 'canceled'

Penjelasan alur nya menurut bayangan saya:
1. `draft` belum bisa diliat admin, setelah `need_review` baru bisa
1.  Nanti bahkan bisa `need_review` & `need_edit` berkali2 sampai akhirnya `ready` atau `canceled`
  - `need_review` (penulis soal->reviewer)
  - `need_edit` (reviewer->penulis soal)
1. Dari `ready` nanti perlu dieliminasi beberapa soal, harusnya masuk jadi `reserve` & `canceled`, yg `ready` yg masuk Bebras Challenge saya rasa ga perlu label tambahan, WDYT?

Dari alurnya berarti:
- Script pemilih soal tiap minggu cukup ngefilter `ready` (mungkin kedepannya `reserve` bisa juga tapi perlu dicek ke dosen2)
- Admin bisa ngeliat `need_review`, `need_edit`, `ready`, `reserve` saja cukup

Undang2 juga @temanaziz @gmochid @haqqer buat ngomenin

**Comment by temanaziz** [comment]
Pertanyaan saya:
1. Perubahan `draft` menjadi `need_review` siapa yang melakukan?
2. Kenapa perlu dipisah antara `draft` dengan `need_review`? Apa bedanya?

**Comment by atnanahidiw** [comment]
Thanks for the question 🙇

Statusnya saya sotoy definisikan dari flow pembuatan soal secara general saja sih (first principle).
Bagus untuk abstraksi tapi mungkin tidak perlu diimplementasi secara keseluruhan.
Seperti misalnya untuk milestone yg sekarang karena langsung dari export XML moodle yang sudah "jadi", bisa kita skip status nya menjadi langsung `need_review`.

Untuk menjawab pertanyaan:

(1) Perubahan `draft` menjadi `need_review` siapa yang melakukan?
>  - need_review (penulis soal->reviewer)

Dalam bayangan saya nantinya akan ada "penulis soal" yg mengerjakan (dan mungkin akan memakai platform lain bukan mobile app). Sekali lagi,
> untuk milestone yg sekarang karena langsung dari export XML moodle yang sudah "jadi", bisa kita skip status nya menjadi langsung `need_review`

(2) Kenapa perlu dipisah antara draft dengan need_review? Apa bedanya?
Agar lebih verbose / jelas, bedanya
> 1. draft belum bisa diliat admin, setelah need_review baru bisa

**Comment by temanaziz** [comment]
Saat ini: 
default all soal = `ready`

Setelah soal 2020 siap, ada beberapa yg kita anggap bagus, default-nya menjadi `need review`, lalu kita ubah satu per satu menggunakan fitur admin.
