### ISSUE TITLE
Issue Image yang tidak tampil karena menggunakan storage Firebase

### ISSUE THREAD

**Issue by gmochid** [ia-toki/bebras-pandai#120]
Semua image yang ditaruh di firebase storage, tidak bisa digunakan ketika di-render menggunakan renderer HTML dari flutter

**Comment by atnanahidiw** [comment]
Kemungkinan karena SVG format, CMIIW
<img width="520" alt="image" src="https://github.com/ia-toki/bebras-pandai/assets/1970083/78b68edb-33c7-41cc-96ab-6691cbc743da">

Alternatif solusi:
1. ganti `cached_network_image` -> `cached_network_svg_image` ([referensi](https://github.com/Baseflow/flutter_cached_network_image/issues/383#issuecomment-1583983983))

**Comment by gmochid** [comment]
Current Condition
- SVG sudah bisa tampil
- Jika besarnya SVG lebih dari screen HP, masih belum ketemu caranya untuk dikecilkan

**Comment by gmochid** [comment]
Close this issue for now, since we still don't have a clear path to resolve this
