### ISSUE TITLE
Menyelesaikan Landing Page

### ISSUE THREAD

**Issue by gmochid** [ia-toki/bebras-pandai#121]

**Comment by attaf-riski** [comment]
Hello, I'm one of semarang programmer member, How can I contribute to this project if I'm a web developer?

**Comment by temanaziz** [comment]
Desain: https://www.figma.com/file/eDtFznahR3LyXt3H8OSRNF/Bebras-Landing-Page-Mockup?type=design&node-id=0-1&mode=design&t=WWzCyo06D0xYFDZj-0

**Comment by haqqer** [comment]
https://bebras-landing-page.vercel.app/
