### ISSUE TITLE
Bug Soal 2020

### ISSUE THREAD

**Issue by temanaziz** [ia-toki/bebras-pandai#132]
Bug:
![image](https://github.com/ia-toki/bebras-pandai/assets/137871192/fdc12721-e7d4-4f45-843c-2f93be858c8d)

1. Soal 2020-PH-02a-I-011-B_Robot_Maze_Game kalau isiannya diisi 30 atau angka yg belakangnya 0, hasilnya gini
2. Hasil gini muncul juga di soal 2020-IN-12-I-000-Pancake. Jawabannya pilihan ganda bentuk pangkat. Tapi model jawaban serupa juga muncul di soal lain dan gak masalah.

**Comment by gmochid** [comment]
Root case
- Error happened when the correct answer of the task is null

Action

- [ ] This task has to be excluded from active tasks @haqqer. In the future if we stumbled upon this kind of error again, then we can take the question out.
- [ ] Should we add correct answer validation when we publish the task from the admin menu? cc @temanaziz

**Comment by gmochid** [comment]
Dari hasil eksplorasi @haqqer 

### Tipe Soal Matching
Ternyata ada tipe soal "MATCHING" yang masuk. Tipe MATCHING ini tidak ada jawaban yang nilainya 100, sehingga tidak ditemukan correct answernya. 

![image](https://github.com/ia-toki/bebras-pandai/assets/1681647/ef91f316-f6ee-4d9c-a946-809fc78a3af4)

Solusinya, kita turunkan dulu semua soal yang tipe-nya matching

### Tipe Soal Multiple Choice yang Tidak Ada Correct Answer
Dari semua answer yang diberikan, tidak ada yang nilainya 100. Most likely tipe ini yang memang multiple choice dan punya beberapa jawaban yang user-nya harus menjawab dengan benar.

![image](https://github.com/ia-toki/bebras-pandai/assets/1681647/8f416c7e-e2bd-4849-84fb-254fbd34f8ed)

### Thoughts

Mungkin saja nanti kita perlu membuat sistem kita modelnya sama persis dengan yang ada di moodle. Tidak pelru correct answer, hanya kita simpan nilai dari masing-masing jawaban
