### ISSUE TITLE
Remove Task Title

### ISSUE THREAD

**Issue by gmochid** [ia-toki/bebras-pandai#134]
![image](https://github.com/ia-toki/bebras-pandai/assets/1681647/cf348529-cb55-4f8f-b13c-bb36c346b22f)

Since all of the task imported from Moodle already has title in the description, then we might remove the task title right above title from the page.

cc @atnanahidiw

**Comment by gmochid** [comment]
Task ini tidak jadi dikerjakan karena tidak semua title task yang ada di deskripsi itu readable. Sehingga section title tetap akan dipertahankan

**Comment by atnanahidiw** [comment]
Kalau begitu bagaimana kalau yang di description saja yg dihapus?
