### ISSUE TITLE
[Task] Quiz - Enable download Quiz BebrasTask data & redirect flow to Quiz exercise

### ISSUE THREAD

**Issue by atnanahidiw** [ia-toki/bebras-pandai#25]
# Description
After we have successfully registered for the quiz and gotten the `weekly_quiz_participation` ID, make local storage collections to save the following data with `weekly_quiz_participation` ID as the key:
- `weekly_quiz_participation`: for reference & update the attempts data
- `weekly_quiz_configuration`: a parsed `running_weekly_quiz` or `next_weekly_quiz` (based on what the user chooses) filtering the important config field only
- `weekly_quiz_task_set`: a list object of task set (question) to be displayed in the quiz exercise 

Note: several redundant data are intentional to make access easier

## Data structure
`weekly_quiz_participation`
as is

`weekly_quiz_configuration`
```
<weekly_quiz_participation id> : {
    "title": ,
    "id": ,
    "created_at": ,
    "start_at": ,
    "end_at": ,
    "challenge_group": ,
    "max_attempts": ,
    "duration_minute": ,
    "sponsors": ,
}
```
value of `max_attempts`, `duration_minute`, `sponsors` is filtered based on `challenge_group` choosen

`weekly_quiz_task_set`
map<id, list<bebras_task>>

## Discussion
How to store the data locally?
-  Menggunakan Local Storage

Struktur Data Local Storage
- "running_weekly_quiz" -> berisi ID quiz yang aktif
- "quiz_[ID Quiz Active]" -> berisi json quiz + json task_set -> ini dipisah 2 saja

# Delivery
- [ ] Parser json dari dan menuju Local Storage
- [ ] Ambil data dari Firestore dan simpan di local storage

**Comment by gmochid** [comment]
- Perlu klarifikasi dari @atnanahidiw tentang behavior download Quiz BebrasTask. Ini akan berpengaruh ke solusi yang dipilih untuk menyimpan data tersebut.

- Redirect flow to Quiz Exercise mungkin bisa dipindah ke separate issue

**Comment by gmochid** [comment]
@atnanahidiw clarification
- Quiz BebrasTask dapat diakses tanpa internet

Gimana menyimpan data di local?
- Menggunakan Local Storage

Struktur Data Local Storage
- "running_weekly_quiz" -> berisi ID quiz yang aktif
- "quiz_[ID Quiz Active]" -> berisi json quiz + json task_set

Task 
- [ ] Parser json dari dan menuju Local Storage
- [ ] Ambil data dari Firestore dan simpan di local storage
