### ISSUE TITLE
[Task] Quiz - Add Starting Page in the Quiz exercise

### ISSUE THREAD

**Issue by atnanahidiw** [ia-toki/bebras-pandai#32]
# Description
![image](https://github.com/ia-toki/bebras-pandai/assets/1970083/f19201f4-a587-4a5d-828f-e6063db184bd)

<br>

### UI/UX
A page before starting every exercise, functioning as / has content of:
- Step by step & screenshot on how to do the exercise
- Info about the number of tasks & duration based on challenge group (sikecil, siaga, etc)
- A checkbox for consent (sudah membaca petunjuk, akan menjawab jujur, dkk)
  the `Mulai` button is disabled if the checkbox isn't agreed / enabled

Next development:
- customizable page if we have a sponsor

I propose using an HTML viewer so we can update the page easily, but I still can't imagine the detail

### Feature
The starting page can be used to inform the user that:
- the timer is started after the user click `Mulai`
- the exercise isn't saved until all tasks are answered or the time is up
- the timer will be reset if the user clicks back or the app is closed, also the attempt will not be counted

# Delivery
- [ ]

**Comment by gmochid** [comment]
Kalau case orangnya sudah pernah attempt, tapi masih ada sisa kuota bakal gimana UI-nya? @atnanahidiw

**Comment by atnanahidiw** [comment]
Good question, tombol dua2nya possible ya (`Mulai` & `Lihat Nilai`) 🤔
Bikin 2 tombol kalau gitu @gmochid, perlu ngecek state lagi buat tau nyala mati tombolnya 🙏

**Comment by atnanahidiw** [comment]
Jadi gini ya (abu2 -> disabled)
![image](https://github.com/ia-toki/bebras-pandai/assets/1970083/8c606022-4e86-4afc-b384-443833ee6076)

**Comment by atnanahidiw** [comment]
Wah kaya gimana itu idenya? Boleh2 diskusi dulu di issue ini yuk
Ga usa dicoding dulu buat matengin idenya gapapa

Kalau bisa dibikinin ilustrasi juga, bisa edit2 excalidraw ini 🙇
https://excalidraw.com/#json=uOObNoaK3zSBEW7W9YUQq,fkYdZOnRNMoRmLle0abxvg

**Comment by gmochid** [comment]
Kalau sekarang

1. Halaman Start Quiz 

    - Berisi 1 hasil quiz terakhir saja.
    - Berisi peraturan dan checkbox, yang mana ini hanya kepakai kalau mau mulai. Kalau mau lihat nilai saja enggak perlu checkbox ini juga
    - Tombol Mulai ke nomor 2, tombol Lihat Nilai ke nomor 3

2. Halaman Lihat Nilai

   - Masih hanya bisa lihat 1 nilai terakhir saja

3. Halaman Quiz

   - Peserta mengerjakan quiz
   - Setelah quiz selesai masuk ke halaman 2.

Proposal rangkaian page dari saya begini

1. Halaman Summary Quiz
   - Berisi informasi tentang quiz, jumlah soal dan berapa attempt tersisa
   - Berisi nilai2 dari semua attempt yang sudah pernah dikerjakan. Jadi siswa bisa membandingkan percobaan2 yang pernah dilakukan. Capability ini enggak ada di flow existing
   - Action menjadi cuman 1: yaitu Start Quiz

2. Halaman Pra Quiz
   - Sebelum masuk quiz, semua peraturan bisa ditulis di sini dan checkbox setuju ditaruh di sini
   - Tombol next / mulai diarahkan ke Halaman Quiz

3. Halaman Quiz
   - Peserta mengerjakan quiz
   - Jika selesai, akan masuk ke halaman 1 sekalian melihat hasilnya

Advantages utama dari flow proposal ini adalah Halaman Summary Quiz bisa memberikan overview lebih baik ke siswa

**Comment by atnanahidiw** [comment]
Hmmm, ini gimana kalau kita rearrange aja?

Lihat Nilai -> Summary Quiz
- mungkin perlu rename `result_page` jadi `summary_page`, dan perlu disisipin tambahan2 info lainnya
- utilize condition yg di PR kemarin kita comment bareng2
    `if not empty to summary_page, else to pra_quiz_page / starting_page`
- di `summary_page` nya sendiri ada beberapa modifikasi
    kalau dari halaman register / list
    - title jadi `LATIHAN SEBELUMNYA`
    - ada button kanan/kiri buat geser skor2 history (atau mungkin dibikin carousel :p)
    - ada tombol `Lanjut` yg redirect ke `pra_quiz_page / starting_page`
    
    kalau dari halaman exercise:
    - title tetep `LATIHAN SELESAI`
    - kasih tombol `Kembali` aja biar ngerefresh dari halaman register
 
Masih galau gimana bikin halaman yg "fun" ketika exercise selesai (ada gambar) atau mau bikin yg infonya banyak (sepi ga ada gambar) ^^a

**Comment by atnanahidiw** [comment]
> [Hmmm, ini gimana kalau kita rearrange aja? Lihat Nilai direplace Summary Quiz..](https://github.com/ia-toki/bebras-pandai/issues/32#issuecomment-1804845780)
Bung @gmochid lanjut diskusi ini yuk. \
WDYT dengan flow nya?

**Comment by gmochid** [comment]
<img width="454" alt="image" src="https://github.com/ia-toki/bebras-pandai/assets/1681647/70219f2b-21d9-4be7-a699-390e2e2859ca">

Pendapatku flownya bisa dibikin jadi gini sih. Jauh lebih simpel IMHO. Setiap kali dari Quiz Registration selalu ke Summary

**Comment by atnanahidiw** [comment]
Iya juga ya, okok, lanjuuut 🚀
Tampilan Quiz Summary reuse yg result page aja sekarang atau bikin baru bung @gmochid?
