### ISSUE TITLE
[Task] Lihat Materi - Add print functionality

### ISSUE THREAD

**Issue by atnanahidiw** [ia-toki/bebras-pandai#40]
# Description
Make print functionality in preview pdf page like the video below
<video src="https://user-images.githubusercontent.com/1970083/277564715-4e667bd1-6d43-4024-bd10-3e6b2ccd734b.mp4" data-canonical-src="https://user-images.githubusercontent.com/1970083/277564715-4e667bd1-6d43-4024-bd10-3e6b2ccd734b.mp4" controls="controls" muted="muted" class="d-block rounded-bottom-2 border-top width-fit" style="max-height:640px; min-height: 200px">
</video>

# Delivery
- [ ] search & research first the available library we can use to enable the functionality, then discuss it in this issue's comment

**Ultimate**
- [ ] Working print functionality

**Comment by 12henbx** [comment]
flutter package: https://pub.dev/packages/printing
video tutorial: https://www.youtube.com/watch?v=IIL98JLOgTM

can run on ios, android
verified publisher by pub dev

**Comment by atnanahidiw** [comment]
okay then, that widget seems to cover our need

**let's continue to implement it in the code then**

N.B. next time maybe can put several pictures to illustrate the report better 👍
