### ISSUE TITLE
[Task] Ops - Hidden Admin menu to preview all of the Bebras Tasks

### ISSUE THREAD

**Issue by atnanahidiw** [ia-toki/bebras-pandai#83]
# Description
For easier ops debugging capability, we need to create a preview page of the Quiz Exercise in the app

# Delivery
- [ ] add field `"isAdmin": false` in the `registered_user` when registering
- [ ] add logic to check user's `isAdmin` in the setting page & display `Lihat Bebras Task` button if `isAdmin == true`
    **don't forget to hide the button back when `isAdmin == false`**
- [ ] add a page of ListView with the item's title from `doc.id`
- [ ] make an exercise preview page reusing the quiz exercise page, but the answer button is removed/disabled

**Comment by gmochid** [comment]
Secara flow, mau ditaruh di Main Menu ya?

**Comment by atnanahidiw** [comment]
💯 yang [Setting page](https://github.com/ia-toki/bebras-pandai/blob/main/app/lib/features/main/presentation/pages/setting_page.dart) tapi ya
Button nya pepetin `Logout` aja biar sering salah pencet 😈
